### ISSUE TITLE
If a players name is too long it messes with the formatting

### ISSUE THREAD

**Issue by MlgEpicCar** [MlgEpicCar/playerlist#10]
idk what to write here

**Comment by besser435** [comment]
![image](https://github.com/user-attachments/assets/b96f8731-ab79-4990-99d6-7b9d338de74c)
If you mean this, we could maybe fix it by making the card size the length of the longest username, or shrinking the usernames to fit. Could maybe also just remove the player head skin since we have the body render, but idk what your vision is.
I'm bad at CSS so maybe debuggy could help.
